---
name: Build Plugin

on:
  workflow_call:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        type: string
        default: 'both'
      project-name:
        description: 'Name of the project (used to name the final plugin files). Defaults to the name of the repository if not provided.'
        required: false
        type: string
        default: ''
      release-mode:
        description: 'Config for HISE build.  (CI, Release, or "Minimal Build", etc)'
        required: false
        type: string
        default: 'CI'
      juce-branch:
        description: 'Branch of JUCE to use for the build (juce6, juce8)'
        required: false
        type: string
        default: 'juce6'
      use-ipp:
        description: 'Whether to install and use Intel IPP (only used for Windows build)'
        required: false
        type: boolean
        default: false
    secrets:
      MACOS_CERTIFICATE:
        required: true
      MACOS_CERTIFICATE_PWD:
        required: true
      MACOS_CERTIFICATE_NAME:
        required: true
      MACOS_CI_KEYCHAIN_PWD:
        required: true
      MACOS_NOTARIZATION_APPLE_ID:
        required: true
      MACOS_NOTARIZATION_TEAM_ID:
        required: true
      MACOS_NOTARIZATION_PWD:
        required: true

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      project-name: ${{ steps.project-name.outputs.result }}
    steps:
      - name: Set Project Name
        id: project-name
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const fullRepository = "${{ github.repository }}";
            const repositoryName = fullRepository.split('/')[1];
            console.log(`Repository name: ${repositoryName}`);
            const projectName = "${{ inputs.project-name }}" == "" ? repositoryName : "${{ inputs.project-name }}";
            console.log(`Using Project Name: ${projectName}`);
            return projectName;

  build-macos:
    needs: pre-build
    if: ${{ inputs.platform == 'both' || inputs.platform == 'macos' }}
    runs-on: macos-latest
    steps:
      - name: Cache HISE build
        id: cache-hise
        uses: actions/cache@v4
        with:
          path: HISE
          key: ${{ runner.os }}-hise-${{ inputs.release-mode }}-${{ inputs.juce-branch }}-${{ hashFiles('HISE/tools/auto_build/build_ci.sh', 'HISE/tools/SDK/sdk.zip') }}
          restore-keys: |
            ${{ runner.os }}-hise-${{ inputs.release-mode }}-${{ inputs.juce-branch }}-
            ${{ runner.os }}-hise-

      - name: Checkout HISE repository
        uses: actions/checkout@v6
        with:
          repository: eschirle/HISE
          ref: 'main'
          clean: true
          submodules: false
          path: eshurl

      - name: Checkout HISE repository
        if: steps.cache-hise.outputs.cache-hit != 'true'
        uses: actions/checkout@v6
        with:
          repository: christophhart/HISE
          ref: 'develop'
          clean: true
          submodules: false
          path: HISE

      - name: Checkout JUCE submodules
        if: steps.cache-hise.outputs.cache-hit != 'true'
        run: |
          cd HISE
          git submodule update --init --recursive
          cd JUCE
          git checkout ${{ inputs.juce-branch }}

      - name: Replace HISE autobuild scripts with eshurl
        run: |
          cp -R eshurl/tools/auto_build/* HISE/tools/auto_build/
          cp -R eshurl/scripts/* HISE/scripts/

      - name: Build HISE
        if: steps.cache-hise.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/HISE/tools/auto_build/
        run: |
          # Unzip SDK
          unzip -o ${{ github.workspace }}/HISE/tools/SDK/sdk.zip -d ${{ github.workspace }}/HISE/tools/SDK/

          sh ./build_ci.sh "${{ inputs.release-mode }}" --skip-tests-and-export

      - name: Checkout Current Repository
        uses: actions/checkout@v6
        with:
          path: app
          lfs: true
      
      # Copy everything from app folder to root
      - name: Copy app folder to root
        run: |
          cp -R ${{ github.workspace }}/app/* .

      - name: Build Plugin
        run: |
          # Copy scripts to root and run
          cp ./HISE/scripts/* .
          sh ./build.sh

      # TODO: Create a release on the repo and upload files there
      - name: Copy VST3 to root
        run: |
          cp -R Binaries/Builds/MacOSX/build/Release/*.vst3 ${{ github.workspace }}/
          cp -R Binaries/Builds/MacOSX/build/Release/*.component ${{ github.workspace }}/
          # cp -R Installer/*.app ${{ github.workspace }}/

      - name: Detect VST file
        id: detect-vst
        run: |
          # Find vst3 file within the github workspace and write the path to the output variable
          vst3_path=$(find ${{ github.workspace }} -name "*.vst3" -print -quit)
          component_path=$(find ${{ github.workspace }} -name "*.component" -print -quit)
          app_path=$(find ${{ github.workspace }} -name "*.app" -print -quit)
          echo "Found VST3 file at: $vst3_path"
          echo "vst3_path=$vst3_path" >> $GITHUB_OUTPUT
          echo "Found Component file at: $component_path"
          echo "component_path=$component_path" >> $GITHUB_OUTPUT
          echo "Found App file at: $app_path"
          echo "app_path=$app_path" >> $GITHUB_OUTPUT
          ls -la ${{ github.workspace }}/*.vst3
          ls -la ${{ github.workspace }}/*.component

      # Upload unsigned artifacts to be used by next job
      - name: Upload Unsigned Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ needs.pre-build.outputs.project-name }}-unsigned-macos
          path: |
            *.hr1
            *.vst3
            *.component
            *.app

  codesign-macos:
    needs: [pre-build, build-macos]
    if: ${{ github.event.inputs.platform == 'both' || github.event.inputs.platform == 'macos' }}
    runs-on: macos-latest
    steps:
      - name: Download unsigned plugin artifact
        uses: actions/download-artifact@v7
        with:
          name: ${{ needs.pre-build.outputs.project-name }}-unsigned-macos

      - name: Find Downloaded Artifacts
        id: find-files
        run: |
          vst3_path=$(find . -maxdepth 1 -name "*.vst3" -print -quit)
          component_path=$(find . -maxdepth 1 -name "*.component" -print -quit)
          app_path=$(find . -maxdepth 1 -name "*.app" -print -quit)
          
          echo "vst3_path=$vst3_path" >> $GITHUB_OUTPUT
          echo "component_path=$component_path" >> $GITHUB_OUTPUT
          echo "app_path=$app_path" >> $GITHUB_OUTPUT
          
          echo "Found VST3: $vst3_path"
          echo "Found Component: $component_path"
          echo "Found App: $app_path"

      # Sign the plugin for MacOS
      - name: Setup Code Signing Keychain
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.MACOS_CERTIFICATE_NAME }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.MACOS_CI_KEYCHAIN_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          
          security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain 
          security default-keychain -s build.keychain
          security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain

          # We finally codesign our app bundle, specifying the Hardened runtime option
          /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_NAME" --options runtime "${{ steps.find-files.outputs.vst3_path }}" -v

      - name: Codesign Component
        if: ${{ steps.find-files.outputs.component_path != '' }}
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.MACOS_CERTIFICATE_NAME }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.MACOS_CI_KEYCHAIN_PWD }}
        run: |
          codesign --deep --force --options runtime -s "$MACOS_CERTIFICATE_NAME" "${{ steps.find-files.outputs.component_path }}" --timestamp
          codesign -dv --verbose=4 "${{ steps.find-files.outputs.component_path }}"

      - name: Notarize VST3 bundle
        env:
          MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
          MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
          MACOS_NOTARIZATION_PWD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
        run: |
          echo "Create keychain profile"
          xcrun notarytool store-credentials "notarytool-profile" --apple-id "$MACOS_NOTARIZATION_APPLE_ID" --team-id "$MACOS_NOTARIZATION_TEAM_ID" --password "$MACOS_NOTARIZATION_PWD"

          echo "Creating temp notarization archive"
          ditto -c -k --keepParent "${{ steps.find-files.outputs.vst3_path }}" "notarization.zip"

          echo "Notarize app"
          xcrun notarytool submit "notarization.zip" --keychain-profile "notarytool-profile" --wait

          echo "Attach staple"
          xcrun stapler staple "${{ steps.find-files.outputs.vst3_path }}"

      - name: Notarize Component if found
        if: ${{ steps.find-files.outputs.component_path != '' }}
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.MACOS_CERTIFICATE_NAME }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.MACOS_CI_KEYCHAIN_PWD }}
        run: |
          echo "Notarizing Component bundle"
          ditto -c -k --keepParent "${{ steps.find-files.outputs.component_path }}" "component_notarization.zip"
          xcrun notarytool submit "component_notarization.zip" --keychain-profile "notarytool-profile" --wait
          xcrun stapler staple "${{ steps.find-files.outputs.component_path }}"

      # - name: Notarize Installer if found
      #   env:
      #     MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      #     MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      #     MACOS_CERTIFICATE_NAME: ${{ secrets.MACOS_CERTIFICATE_NAME }}
      #     MACOS_CI_KEYCHAIN_PWD: ${{ secrets.MACOS_CI_KEYCHAIN_PWD }}
      #   run: |
      #     if [ -e "${{ steps.find-files.outputs.app_path }}" ]; then
      #       echo "Notarizing Installer app"
      #       ditto -c -k --keepParent "${{ steps.find-files.outputs.app_path }}" "installer_notarization.zip"
      #       xcrun notarytool submit "installer_notarization.zip" --keychain-profile "notarytool-profile" --wait
      #       xcrun stapler staple "${{ steps.find-files.outputs.app_path }}"
      #     fi
      
      - name: Zip Everything
        run: |
          zip -r "${{ needs.pre-build.outputs.project-name }}-macos.zip" *.vst3 *.hr1 *.component *.app

      - name: Upload Plugin Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ needs.pre-build.outputs.project-name }}-macos
          path: |
            ${{ needs.pre-build.outputs.project-name }}-macos.zip



  # TODO: Fix Windows build - currently failing due to UseIPP flag mismatch
  build-windows:
    needs: pre-build
    if: ${{ github.event.inputs.platform == 'both' || github.event.inputs.platform == 'windows' }}
    runs-on: windows-latest
    env:
      RELEASE_MODE: "CI"
      JUCE_BRANCH: "juce6"
    steps:
      # TODO: Is this cleanup step needed?
      - name: Cleanup working dir (?)
        run: del *.* /Q /S
        shell: cmd

      - name: Checkout HISE repository
        uses: actions/checkout@v6
        with:
          repository: eschirle/HISE
          ref: 'develop'
          clean: true
          submodules: false
          path: HISE

      - name: Checkout JUCE submodules
        shell: cmd
        run: |
          cd HISE
          git submodule update --init --recursive
          cd JUCE
          git checkout ${{ env.JUCE_BRANCH }}

      - name: Install Intel IPP via pip
        run: pip3 install ipp-static

      - name: Setup MSBuild and VS Dev Environment
        uses: microsoft/setup-msbuild@v2
        with:
          #vs-prerelease: true # This did not include v145
          msbuild-architecture: x64
          
      - name: Build HISE CI
        working-directory: ${{ github.workspace }}/HISE/tools/auto_build/
        shell: cmd
        run: |
          chdir
          dir
          build_ci.bat "${{ env.RELEASE_MODE }}" --skip-tests-and-export

      - name: Checkout Current Repository
        uses: actions/checkout@v6
        with:
          path: app
          lfs: true

      - name: Copy app folder to root
        run: Copy-Item -Path "${{ github.workspace }}/app/*" -Destination "${{ github.workspace }}" -Recurse -Force
        shell: pwsh

      - name: Build Plugin
        shell: cmd
        run: |
          copy HISE\scripts\* .
          build.bat

      - name: Copy VST3 to root
        shell: pwsh
        run: Copy-Item -Path "${{ github.workspace }}/Binaries/Builds/Windows/build/Release/*.vst3" -Destination "${{ github.workspace }}" -Recurse -Force

      - name: Upload Dyes Tonguewuhh
        uses: actions/upload-artifact@v7
        with:
          name: ${{ needs.pre-build.outputs.project-name }}-windows
          path: |
            *.hr1
            *.vst3


